### ISSUE TITLE
Add to f-droid

### ISSUE THREAD

**Issue by quwepiro** [AndroidNewbies/Sanxing#3]
How about adding your app to f-droid as it does not use any proprietary libraries and is completely open-source?

**Comment by celestialphineas** [comment]
That's great. I'd be appreciated. Please feel free to distribute the app, though it's no longer maintained. Hopefully this will help someone.

**Comment by quwepiro** [comment]
All right. I already created a fork where I made some small enhancements.
So is it okay for you if I use my fork for adding to f-droid or should I use your codebase.
Of course, you will be noticed as the author, not me :wink:

**Comment by celestialphineas** [comment]
You are welcomed to make any modifications on the fork and adding the app to f-droid. We'll appreciate it, for we may not have much time to work for the distribution part. Actually, I feel honored. After all, this was just a class project. Pull requests are also welcomed. 😊

P.S. I'm not the only developer of this app. [Aron Lin](https://github.com/AronLin) and [Ken Geng](https://github.com/KenGeng) did even more. We were a team.

**Comment by quwepiro** [comment]
Perfect. I will try if I can add multiple authors.
Btw I have made a small compilation of available floss android habit apps https://github.com/quwepiro/foss-habit-apps beside the popular Loop Habit Tracker
